### ISSUE TITLE
Request for .NET 4.0 version

### ISSUE THREAD

**Issue by brad508** [NLog/NLog-Contrib#12]
Would it be possible to publish a nuget package that is built againt the 4.0 runtime?

**Comment by Xharze** [comment]
The source code now supports .NET 4.0, a new package will be released soon

**Comment by brad508** [comment]
When will a nuget package be released?

**Comment by 304NotModified** [comment]
2 june

**Comment by 304NotModified** [comment]
This hasn't been resolved I think.

**Comment by 304NotModified** [comment]
I see it's .net 4.5 only still

**Comment by 304NotModified** [comment]
This has been fixed with 

https://github.com/NLog/NLog/pull/884

and the release of NLog 4.1, see: http://nlog-project.org/2015/08/31/nlog-4-1-0-is-now-available.html
