### ISSUE TITLE
Application is not filled in Elmah SQL server Table

### ISSUE THREAD

**Issue by neothoms** [NLog/NLog-Contrib#20]
Hello, I have tried Nlog.Elmah and it is working but the application column in Elmah Table is not filled.
The result is that NLog Informations are not displayed with Elmah.axd

Is there a configuration that I have missed ?

**Comment by toddmeinershagen** [comment]
I am not sure that the Application is being populated from NLog settings.  We might be able to add this as a feature.  Maybe if there is a custom variable set up in NLog (appName or something like that) it could by convention use that property.  Unfortunately, NLog doesn't have that property built-in by default.

**Comment by neothoms** [comment]
I understand that the property may not be in Nlog but It would be nice if we could force it somewhere for Elmah.

**Comment by toddmeinershagen** [comment]
Okay.  So, as I said, the only way to do that would be to allow for a custom NLog variable that if it is there would be sent.  I can try to work on that as an item in the near future.  Let you know when complete.

**Comment by toddmeinershagen** [comment]
I looked again at this and found that you can specify the application name when you configure your ```<elmah>``` element in your associated web.config or app.config - not in the nlog.config.  

Below is an example:

```
<elmah>
     <errorLog 
          type="Elmah.SqlErrorLog, Elmah" 
          applicationName="MyApp" 
          connectionStringName="DBConnectionStringName" 
     />
</elmah>
```

**Comment by neothoms** [comment]
Thank you, it works very well.
