### ISSUE TITLE
Consider assigning strong name to NLog.Contrib.dll

### ISSUE THREAD

**Issue by kylelib** [NLog/NLog-Contrib#27]
I'm trying to make use of NLog.Contrib features in BizTalk. Sadly BizTalk requires strong named assemblies. I'm deploying using NuGet package manager and would prefer not to maintain my own version of the assembly simply to have it strong named.

Thanks

**Comment by 304NotModified** [comment]
We will discuss this. I think it's a valid request.

Please not that we are splitting the nlog-contrib package into smaller / other packages.

**Comment by 304NotModified** [comment]
Which part do you need from the NLog.Contrib?

**Comment by kylelib** [comment]
@304NotModified, specifically, we are interested in the ```MappedDiagnosticsLogicalContext``` feature. 

We have a SaaS architecture of sorts with several services being orchestrated by BizTalk. The ```MappedDiagnosticsLogicalContext``` feature gives us the ability to carry a subscription identifier with each message traversing the system that each service can log along the way to help us correlate service calls when issues arise. Because BizTalk applications are loaded and run within the context of the BizTalk process, dependent assemblies are only resolvable via the Global Assembly Cache which requires those assemblies to be strong named.

Sadly NLog's ```GlobalDiagnosticLogicalContext``` does not solve our problem because we need the subscription id to be honored in the synchronization context of the current thread and not Thread Local Storage.

I'm interested in hearing more about the refactor of **nlog-contrib** into *smaller/other packages*. Where can I find and track more the progress?

**Comment by 304NotModified** [comment]
Hi,

This is an actual topic :)

We are moving the contrib part to the core (NLog) for NLog 4.1, so it will be strong named

We released a RC for 4.1 yesterday: https://www.nuget.org/packages/NLog/4.1.0-rc1

**Comment by kylelib** [comment]
Great!!! I'll be checking it out for sure.

**Comment by 304NotModified** [comment]
@kylelib 

I never used the MDLC myself. Can you explain me why you use MDLC and not the MDC? I should be one the docs (wiki) :)

**Comment by 304NotModified** [comment]
This is fixed with the release of NLog 4.1, see http://nlog-project.org/2015/08/31/nlog-4-1-0-is-now-available.html

**Comment by kylelib** [comment]
@304NotModified 

We're using System.Task and Visual Studio Async in our api and as I understand it MDLC should be used in that case. In the BizTalk scenario I eluded to above we will likely be using MDC.

**Comment by 304NotModified** [comment]
Thanks for the info :)
